export const FETCH_ARTICLE_FULFILLED = '@articles/FETCH_ARTICLE_FULFILLED'
export const FETCH_COMMENTS_FULFILLED = '@articles/FETCH_COMMENTS_FULFILLED'
export const ADD_LIKE_TO_REPLY = '@articles/ADD_LIKE_TO_REPLY'